// lib/labels.ts
import type { LabelObject } from "./types"; // Assuming LabelObject is defined in types.ts

// Default labels that will be used to seed the customLabels in the store
// if no custom labels are found in localStorage.
// We provide enough data for them to become full LabelObjects.
// IDs will be generated by the store if these are used for seeding.
export const DEFAULT_LABEL_DEFINITIONS: Omit<LabelObject, 'id'>[] = [
    { name: "Frontend", emoji: "🎨", color: "#4ECDC4" },
    { name: "Backend", emoji: "⚙️", color: "#45B7D1" },
    { name: "Fullstack", emoji: "🌐", color: "#2AB7CA" },
    { name: "Design", emoji: "🎭", color: "#FED766" },
    { name: "Testing", emoji: "🧪", color: "#FF6B6B" },
    { name: "Documentation", emoji: "📚", color: "#7BC8A4" },
    { name: "Urgent", emoji: "🚨", color: "#F9ADA0" },
    { name: "Deferred", emoji: "⏳", color: "#8A8295" },
] as const;

// Enhanced vibrant color palette for labels
export const VIBRANT_LABEL_COLORS = [
    // Electric Blues & Cyans
    "#00D4FF", // Electric Blue
    "#0099FF", // Bright Blue
    "#00BFFF", // Deep Sky Blue
    "#1E90FF", // Dodger Blue

    // Vibrant Purples & Magentas
    "#8A2BE2", // Blue Violet
    "#9932CC", // Dark Orchid
    "#FF1493", // Deep Pink
    "#FF69B4", // Hot Pink

    // Bright Greens & Emeralds
    "#00FF7F", // Spring Green
    "#32CD32", // Lime Green
    "#00FA9A", // Medium Spring Green
    "#20B2AA", // Light Sea Green

    // Warm & Energetic
    "#FF6347", // Tomato
    "#FF4500", // Orange Red
    "#FFD700", // Gold
    "#FFA500", // Orange

    // Cool Teals & Aquas
    "#00CED1", // Dark Turquoise
    "#48D1CC", // Medium Turquoise
    "#40E0D0", // Turquoise
    "#00FFFF", // Cyan

    // Rich Reds & Corals
    "#DC143C", // Crimson
    "#FF6B6B", // Light Red
    "#FF5722", // Deep Orange
    "#E91E63", // Pink
]

export const getRandomLabelColor = () => {
    return VIBRANT_LABEL_COLORS[Math.floor(Math.random() * VIBRANT_LABEL_COLORS.length)]
}
